name: Existential Inquiry Radio
favicon: null
layout_spectrum: 0.99148
typography_spectrum: 0.206383
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#221b45'
    - '#eac655'
    - '#605b84'
    - '#bf7f27'
    - '#443e11'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
