layout_spectrum: 0.6276596
favicon: null
name: Existential Inquiry Radio
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
  brandColors:
    - '#221b45'
    - '#eac655'
    - '#605b84'
    - '#bf7f27'
    - '#443e11'
typography_spectrum: 0.07362
